- name: Install nginx OSS
  hosts: nuevos
  remote_user: user-ansible
  become: True
  gather_facts: False
  tasks:
  - name: Crear repositorio
    copy:
      src: /etc/yum.repos.d/nginx.repo
      dest: /etc/yum.repos.d/
      owner: root
      group: root
      mode: 0644

  - name: Instalar nginx
    yum:
      name: nginx
      state: latest

  - name: Colocar SElinux en permisivo
    selinux:
      policy: targeted
      state: permissive

  - name: Deshabilitar SElinux
    selinux:
      state: disabled

  - name: Habilitar servicios en firewalld
    firewalld:
      service: "{{ item }}"
      permanent: true
      state: enabled
    with_items:
      - http
      - https

  - name: Reiniciar servicio de firewalld
    service:
      name: firewalld
      state: restarted

  - name: Iniciar servicio de NGINX
    service:
      name: nginx
      state: started
      enabled: yes
