---
- name: Instalar software
  hosts: all
  remote_user: user-ansible
  become: True
  tasks:
  - name: Instalar MariaDB
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - mariadb-server
      - mariadb
